name: residential_booking_app
description: "Damascus University Residential Booking Project"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- UI & Assets ---
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3 # Responsiveness
  cached_network_image: ^3.3.1 # For loading apartment images later

  # --- State Management ---
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^9.2.0 # Dependency Injection

  # --- Functional Programming ---
  dartz: ^0.10.1

  # --- Networking ---
  http: ^1.2.1
  http_parser: ^4.0.2 # CRITICAL: For MediaType in MultipartRequest
  internet_connection_checker: ^3.0.1

  # --- Local Storage ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # --- Utilities ---
  image_picker: ^1.1.2 # For selecting Profile/ID images
  intl: ^0.20.2 # Date formatting
  path_provider: ^2.1.3
  font_awesome_flutter: ^10.12.0
  smooth_page_indicator: ^2.0.1
  google_fonts: ^6.3.3
  dio: ^5.9.0
  awesome_dialog: ^3.3.0
  awesome_snackbar_content: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # --- Code Generation (Added as requested) ---
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/1.jpg
    - assets/icons/
